export const DOMAIN_SUGGESTIONS = [
  "Salon de înfrumusețare",
  "Cabinet stomatologic",
  "Clinică veterinară",
  "Restaurant",
  "Cafenea",
  "Cofetărie",
  "Bar / Lounge",
  "Frizerie",
  "Service auto",
  "Constructor / Renovări",
  "Instalator",
  "Electrician",
  "Cabinet psihologie",
  "Cabinet medical",
  "Kinetoterapie",
  "Fitness / Sală de sport",
  "Yoga / Pilates",
  "Pensiune / Hotel",
  "Agenție imobiliară",
  "Florărie",
  "Croitorie",
  "Fotograf",
  "Videograf",
  "Studio foto",
  "Agenție de marketing",
  "Contabilitate",
  "Avocat",
  "IT / Software",
  "E-commerce",
  "Altele",
];
